eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    statusPageUrl: http://localhost:8761/info
    healthCheckUrl: http://localhost:8761/health
    homePageUrl: http://localhost:8761/
